rootProject.name = "burger"
include("application")
include("persistence")
include("domain")
include("api")
include("interfaces")
include("controller")
include("usecase")
include("entity")
include("gateway")
